GET http://localhost:8080/games

###

POST http://localhost:8080/games
Content-Type: application/json

{
  "name": "Super Mario Bros",
  "releaseDate": "1985-09-13",
  "noOfPlayers": 1
}

###

DELETE http://localhost:8080/1

###

# Add a game to a platform

PUT http://localhost:8080/games/2/platform/1

###

# Remove a game from a platform

DELETE http://localhost:8080/games/2/platform/1