GET http://localhost:8080/game

###

POST http://localhost:8080/game
Content-Type: application/json

{
  "name": "Super Mario Bros",
  "releaseDate": "2011-12-03",
  "noOfPlayers": 1
}

###

DELETE http://localhost:8080/1

###

# Add a game to a platform

PUT http://localhost:8080/game/2/platform/1

###

# Remove a game from a platform

DELETE http://localhost:8080/game/2/platform/1